### ISSUE TITLE
Potential talk

### ISSUE THREAD

**Issue by jnothman** [nlposs/NLP-OSS#12]
@dimazest, @alvations

To take this offline from #1... Firstly I have limited capacity to travel, and NAACL 2018 is probably not feasible.

I'm not sure what interest there is in talking about scikit-learn, but I think a comparative discussion of a few research-related open-source software projects I've been involved in might be of interest.

An alternative topic I've been thinking about lately is the responsibility of the FOSS developer/maintainer to the research and development community, in terms of:
* ensuring correctness 
* facilitating and encouraging best practices through design and documentation (not software engineering best practices here, but things like ML experimental design that avoids data leakage, and reporting the right metrics at the right times; in a NLP context this might mean using stand-off markup where possible to encourage recoverability of the input, always using unicode rather than byte strings, etc.)
* completeness (people will often not bother trying a technique if you do not include it in your package)
* efficiency (people could conceivably choose a different evaluation metric just because your implementation is slow; Matt probably has some comments on how efficiency and public interface are interrelated)
* ensuring continued availability/compatibility

At ICML, there were people making comments like "don't worry about how tricky it is to implement; someone will contribute it to Scikit-learn and you can just use it", with complete disregard for the role of the software maintainer and where the informal liability lands.

With Matt Honnibal and Chris Manning listed as invited talks, it would make for an alarmingly Australian workshop :P

Fyi, @amueller and @vene.

**Comment by amueller** [comment]
Damn, you were at ICML? Makes sense but I missed you again ;) - but wasn't really feasible for me... lmk if/when you come to the states ;) Also I want to hear that talk!

**Comment by alvations** [comment]
@jnothman A talk on any OSS experience and bringing it close the NLP/ML would be great. Examples like the ICML comments could have been openly discussed and it would be good to know the maintainers' perspective on the correctness, availability, efficiency, etc. 

We understand that some of the conferences are harder to travel to for different speakers. But we're subjected to the conference chairs' assignment. Nevertheless, we can surely put you down as a speaker as long as it's not NAACL =) 

Once we get a notice of which conference we can re-confirm about the talk again. Can we put you in as a tentative yes? 😉 

Getting back to the potential talk discussion, the ICML comment would make a great opening slide to any FOSS talk! The topic is open to any related topic up till we hammer down on the program schedule in ~June next year. 

Lets keep this discussion going! Maybe more people will chip in on this.

**Comment by jnothman** [comment]
Tentatively, yes, but with a preference for ACL.

**Comment by alvations** [comment]
Got it! Putting you on the invited speaker list =)

**Comment by jnothman** [comment]
I see the workshop is up for ACL'18! Great! Watching!

I should note that if, in the interests of fixing #15 or otherwise, you see fit to replace my talk, I will understand...

**Comment by jnothman** [comment]
(Also if you have a say in the scheduling, I'd much prefer the workshop appear on Thurs 19 than Fri 20.)

**Comment by alvations** [comment]
Closing this issue. Thank you @jnothman for the very interesting [talk on OSS responsibility](https://nlposs.github.io/) in 2018!! 

Thank you @amueller for being part of 2018 PC and the introduction to @GaelVaroquaux and recommending @jnothman as the invited speaker!!

We'll keep in touch for NLP-OSS 2020 and beyond. 

----

P/S: We'll open an issue to discuss about the invited talks for 2020 once the results of the workshop proposal is out on 20 Oct 2019 =)
