### ISSUE TITLE
Tagline

### ISSUE THREAD

**Issue by alvations** [nlposs/NLP-OSS#16]
As per the request of the call for workshop proposal, we need a tagline for the workshop. 

> **Summary:** A very brief advertisement or tagline for the workshop, up to 140 characters, that highlights any key information you wish prospective attendees to know, and which would be suitable to be put onto a web-based survey.

**Comment by alvations** [comment]
How about "With great scientific breakthrough comes solid engineering and open communities."?

Any other ideas?

**Comment by dimazest** [comment]
It might be a bit too far from the workshop. I mean, it doesn't clearly tell that it's about a workshop about open source software in NLP/CL. Though, I might be wrong.

* "Accelerating great science with open source software"
* "Collective scientific breakthrough with OSS"
* "OSS software makes better NLP research"

these are just ideas

**Comment by alvations** [comment]
@e9t @mhagiwara any suggestions?

**Comment by alvations** [comment]
Lets go with a placeholder: 

> Towards better NLP research with Open Source Software 

Sort of a `OSS software makes better NLP research` + `Collective scientific breakthrough with OSS`?

**Comment by alvations** [comment]
From https://twitter.com/dennybritz/status/922086946330918912

> Democratizing NLP and making the world a better place!

**Comment by alvations** [comment]
@mhagiwara @dimazest @e9t Should we go with `Democratizing NLP!` and close this issue?

@everyone any other comments?

**Comment by dimazest** [comment]
I like "Democratizing NLP!", it's short.

**Comment by alvations** [comment]
`Democratizing NLP!`, it is =)
