### ISSUE TITLE
[NLP-OSS 2020] Program Committee Suggestions/Confirmation

### ISSUE THREAD

**Issue by alvations** [nlposs/NLP-OSS#19]
As like before #1, let's use this issue to track:

- suggestions on new program committee members
- how many confirmed program committee members we have.

Let's streamline the confirmation of PCs and extend the invitation to people we've missed.

 - Anyone on the [shortlist of the proposal](https://github.com/nlposs/NLP-OSS/blob/master/Proposal-2019.md#programme-committee-hopeful-list) that accepts the invitation by commenting in this issue automatically confirms your participation as program committee. Let's also add the affiliations once they're confirmed.

 - Anyone who wants to participate but not in the shortlist, comment in this issue. Then we'll validate and add you to the list if any of the current shortlisted PC give you a thumbs-up. (let's count that as a 'recommendation' from the shortlisted PCs)

 - We'll add anyone that the shortlisted PCs suggested/thumbs-uped to the PC shortlist.

 - We'll add previous PCs into the 2020 workshop if there's no explicit response to step down from the PC

Please do also help us fill up a short survey (~5mins) about the workshop and how we can improve it? https://forms.gle/Ln9icghRaaLcsnPAA  Thank you in advance! 

P/S: Also, ⭐️ the repo if you like the workshop idea! And comment in this issue if you would like to participate as program committee but we missed you in the shortlist.

**Comment by goodmami** [comment]
Confirming my participation! Also I have a change of affiliation: I am now with Nanyang Technological University.

**Comment by tteofili** [comment]
Participation confirmed 👍

**Comment by icedwater** [comment]
I would like to take part next year. Please let me know I can help.

**Comment by flammie** [comment]
I'd be interested to help if I can :-)

**Comment by alvations** [comment]
@goodmami @tteofili @icedwater Thank you for accepting the invitation! 

@flammie Tommi! Definitely glad to have you join us for the workshop! Sending you the invitation email =)

**Comment by jnothman** [comment]
Hi @alvations, I'm happy to remain on the PC. And I hope my workload is a
bit more manageable then!

**Comment by amittai** [comment]
👈🏻👍🏻

**Comment by shamilcm** [comment]
Confirming my participation for NLP-OSS 2020.

**Comment by sdeneefe** [comment]
I'd like to participate in the workshop and the program committee.

**Comment by vene** [comment]
Confirming my participation on the PC. Affiliation:  Instituto de Telecomunicações, Lisbon, Portugal

**Comment by shicode** [comment]
Confirming my participation on the PC!

**Comment by geetickachauhan** [comment]
Confirming my participation on the PC!

**Comment by alinepaes** [comment]
I am glad to accept the invitation to be part of 2020 PC!

**Comment by ggdupont** [comment]
Following the recent open call by Liling Tan on twitter, I filled out the form and I'm volunteering to support the workshop in 2020.

**Comment by ivanvladimir** [comment]
I confirm my participation on the PC

**Comment by svakulenk0** [comment]
Confirmed! Affiliation: University of Amsterdam

**Comment by tttthomasssss** [comment]
Confirmed & very happy to join the PC

**Comment by alvations** [comment]
@jnothman @amittai @shamilcm @vene @shicode @geetickachauhan @alinepaes @ivanvladimir @svakulenk0 Thank you for accepting the invitation!! 

@ggdupont Thank you for the points on the tagline and your interest! We've sent you an email for the invitation =)

**Comment by yvespeirsman** [comment]
Happy to confirm my participation in the PC!

**Comment by sharatsc** [comment]
Happy to confirm my participation in the PC

**Comment by ggdupont** [comment]
I can now confirm too.

**Comment by almoslmi** [comment]
I confirm my participation.

**Comment by bethard** [comment]
Happy to help.

Sorry, I didn't comment earlier because the issue says starring the repository was sufficient, and I had already done that. But I got an email saying you didn't have a confirmation from me, so I guess you need a comment as well.

**Comment by alvations** [comment]
Thank you again for the confirmation @bethard @dennybritz @almoslmi @ggdupont @mhagiwara @yvespeirsman  ! 

Sorry about the confusion, starring the repo worked for the first edition after that we overlooked that it's unclear  for our second edition =) Let me cancel that in the original post of this issue.

**Comment by sandyasm** [comment]
Confirming my participation...

**Comment by fredblain** [comment]
I'm in.

**Comment by mohdsanadzakirizvi** [comment]
Conforming my participation. I'm Sanad. I have two email ids one is the one with which I have registered (work) and the other one is this one.

**Comment by amueller** [comment]
I don't think I'll be able to help for 2020, sorry.

**Comment by alvations** [comment]
@isoboroff @mohdsanadzakirizvi @fredblain @sandyasm @evanmiltenburg Thank you for the confirmation! 

@amueller No worries, we understand. Would you like to be kept in contact for NLP-OSS in the future?

**Comment by amueller** [comment]
@alvations sure, feel free to keep me on stand-by :)

**Comment by mbollmann** [comment]
Happy to confirm, I forgot if I already did so via email :)

**Comment by amittai** [comment]
suggesting @ssloto

**Comment by Ssloto** [comment]
Yes, I am interested

**Comment by alvations** [comment]
Thanks @amueller! We'll keep you in the loop =)

Thank you @mbollmann for the confirmation!

@amittai Thank you for the recommendation! @Ssloto Sending you an official invite =)

**Comment by marziehf** [comment]
Happy to confirm my participation as PC.

**Comment by ancadumitrache** [comment]
Thank you for the invitation, I will gladly be a PC.

**Comment by alvations** [comment]
Thank you @marziehf @ancadumitrache for confirming the invitation!

**Comment by MosheWasserb** [comment]
Thank you for the invitation, I confirm my participation.

**Comment by lefterav** [comment]
Happy to confirm my participation in the PC!

**Comment by Ssloto** [comment]
Happy to confirm my participation as well. :)

**Comment by alvations** [comment]
Thank you @Ssloto @lefterav @MosheWasserb for confirming the invitation!

**Comment by napsternxg** [comment]
I have also confirmed my participation for PC via email. Adding a comment here as well :-)

**Comment by mohdsanadzakirizvi** [comment]
Hi,

I remember we were planning to apply for 4 conferences for 2020:

1. ACL
2. COLING
3. EMNLP
4. AACL

Is there any status update on it so far? Do we need any help from our side
or the community?
Are we going to have an office hours?

I'm happy to help in anyway I can.

Regards
Sanad

**Comment by e9t** [comment]
Hi @mohdsanadzakirizvi!
Please note that the next NLP-OSS workshop will be colocated with EMNLP 2020.

We are currently working on updating the webpage, and once we're done with that, we'll get back to you with some more details and perhaps some requests. Thanks for your support!

**Comment by mohdsanadzakirizvi** [comment]
Hi,
When will we start working for NLP-OSS, what are the dates?

**Comment by mefoster** [comment]
I can participate this time.

**Comment by geetickachauhan** [comment]
Hi @mohdsanadzakirizvi our website has been updated and the papers will be due by July 1, 2020.

**Comment by mohdsanadzakirizvi** [comment]
That sounds great, please let me know whenever/wherever I can help.

Sanad

**Comment by alvations** [comment]
Hi **@everyone**, Thank you again for the accepting the PC invitation! 

We've sent out the updates on the workshop and if you haven't received it, please do ping us so that we can send it out to you. Sorry in advance, if we missed you out and lose track of the emails while sending out the mails.

Please do help to check if your affiliation and name on the site is correct https://nlposs.github.io/2020/index.html and please do tell us if it's wrong =)

If you know of any potential work that is relevant to the workshop, we hope that you can help to encourage submissions and/or participation to the workshop to your local community. We'll be sending out the first call for paper very soon!

Hope we can have a fruitful workshop!! Thank you all again!

**Comment by mohdsanadzakirizvi** [comment]
Hi,

I would like to update my affiliation from "Analytics Vidhya" to "Microsoft
Research India". My full name is " Mohd Sanad Zaki Rizvi".

Thank you,
Sanad

**Comment by mohdsanadzakirizvi** [comment]
Hi,

Could you please check on my previous request?

Thanks
Sanad

**Comment by goodmami** [comment]
@mohdsanadzakirizvi I don't have write access but I created a pull request from my fork to fix your affiliation. See nlposs/nlposs.github.io#24. Note that the change is in the nlposs.github.io repository for the website; if you want to change the proposal in this repository, you can submit a similar PR.

**Comment by e9t** [comment]
@hunkim has also given confirmation directly to me, via Facebook.

**Comment by tttthomasssss** [comment]
Hi my affiliation changed from the `University of Edinburgh` to `Rasa Technologies GmbH`. I have just recently received another invitation for joining the Program Committee on my rasa address (which I accepted).

**Comment by alvations** [comment]
Thank you @tttthomasssss for accepting the softconf invitation!! We've updated your affiliation on the site

**Comment by alvations** [comment]
To all PC members who hasn't received the softconf invitation, we might have missed you out in the invites. Apologies to missing you out.

Ping us at nlposs.workshop@gmail.com and we'll send you the invite asap =)

**Comment by alvations** [comment]
Thank you everyone again for the support and participation in NLP-OSS 2020!! 

It's time for a new edition in 2023 and we'll be honored if you all join us again on #35 and fill up this form on https://forms.gle/dZf2FnbVHPupV29b7 

Hope to see all of you again in the next workshop edition!
