### ISSUE TITLE
Workshop Website Creation

### ISSUE THREAD

**Issue by alvations** [nlposs/NLP-OSS#2]
Let's use this issue to track the progress of the workshop website.

**Comment by e9t** [comment]
So I think there are two easy options to choose from:

1. Google sites: [Like any other workshop website.](https://sites.google.com/site/acl17nmt)
2. Github pages: We can push directly to this repo & publish on gh-pages. We can get pull requests from anyone. We will be open sourcing for OSS, and our actions will speak louder than words.

My choice is rather obvious :)

**Comment by alvations** [comment]
[2] would be the obvious choice =)

**Comment by ines** [comment]
GitHub pages + Jekyll also means the content can be written in Markdown, which will make it even easier for people to edit and contribute.

Depending on the timeline and how busy I am, I'd be happy to help out with the front-end 😊

**Comment by alvations** [comment]
@ines Thanks in advance for the offer! 

I'm bad with front-end things. I'll leave it up to you, @e9t and @mhagiwara to decide on how should the webpage be setup =)

**Comment by alvations** [comment]
I've set up the webpage repo at https://github.com/nlposs/nlposs.github.io =)

**Comment by dimazest** [comment]
A while ago I managed a web page for http://iwcs2015.github.io/

https://github.com/iwcs2015/iwcs2015.github.io uses pelican with a bunch of plugins, it might be useful to get inspiration.

**Comment by mhagiwara** [comment]
Just pushed the initial version of the workshop webpage https://nlposs.github.io/

Closing this issue for now
