### ISSUE TITLE
EMNLP 2020 points to NLP-OSS 2018 website

### ISSUE THREAD

**Issue by goodmami** [nlposs/NLP-OSS#26]
The [EMNLP 2020 workshops site](https://2020.emnlp.org/workshops) is up and the NLP-OSS link goes to nlposs.github.io, which currently is the content from the 2018 workshop. Rather than updating that repo (which could break links), we could create a new `2020` website repository so the link is `nlposs.github.io/2020`. Other ideas?

**Comment by e9t** [comment]
Thanks for the feedback @goodmami! :)
I've just sent a PR at https://github.com/nlposs/nlposs.github.io/pull/16, please check it out.
