### ISSUE TITLE
CFP with some controversy  

### ISSUE THREAD

**Issue by alvations** [nlposs/NLP-OSS#41]
Hi all, I was thinking of posting this draft as part of the CFP mailings later this week to follow up on our 1st and 2nd CFP. https://github.com/nlposs/NLP-OSS/blob/master/CFP-Two-And-A-Half.md

It's a little controversial so I guess it's best to seek everyone's suggestions before we send them. 

@erip @geetickachauhan @jgwinnup @dimazest what do you think about the psuedo-CFP idea?

**Comment by jgwinnup** [comment]
I appreciate the humor on this CFP but it may be problematic for (official) me. I’d prefer to do a regular CFP, which I realize is no fun, but it is more professional.

-Jeremy

**Comment by alvations** [comment]
At least 3 votes for no (myself included), will scrap the idea =)
